# Generated by Django 4.0.2 on 2022-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0002_alter_confirmationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
